# Generated by Django 6.0.7 on 2026-08-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_test_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_post',
        ),
    ]
