# Generated by Django 6.0.7 on 2026-08-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='p',
        ),
    ]
