# Generated by Django 6.0.7 on 2026-08-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_post_comment_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='p',
            new_name='post',
        ),
    ]
